# ansible/inventory/hosts.yml
all:
  children:
    tag_fastapi_vm:
      hosts:
        fastapi:
          ansible_host: 127.0.0.1
          ansible_port: 2222
    tag_mqtt_vm:
      hosts:
        mqtt:
          ansible_host: 127.0.0.1
          ansible_port: 2223